language: c
notifications:
  email: false
compiler: gcc
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libtidy-dev libcurl4-openssl-dev libxml2-dev
script:
  - make
  - make test